[tox]
envlist = pytest, types, lint, format

[testenv:pytest]
dependency_groups =
    test
commands =
    pytest tests \
        --durations=0 \
        --capture=no \
        {posargs}

[testenv:lint]
description = Run code linter
skip_install = True
deps = ruff
commands = ruff check src/ tests/

[testenv:format]
description = Run code formatter check
skip_install = True
deps = ruff
commands = ruff format --diff src/ tests/

[testenv:types]
dependency_groups =
    types
commands =
    ty check src --output-format concise
