name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  pytest:
    name: Python ${{ matrix.python }}
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - run: uv tool install --python ${{ matrix.python }} --with tox-uv tox
      - run: tox run -v --notest --skip-missing-interpreters false
      - run: tox -e pytest
