name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  pytest:
    name: Python ${{ matrix.python }}
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uv tool install --python ${{ matrix.python }} --with tox-uv tox
      - run: tox run -v --notest --skip-missing-interpreters false
      - run: tox -e pytest
